spring.application.name=config-server
server.port=8888

spring.cloud.config.server.git.uri=git@github.com:ptrvio/config-server.git
spring.cloud.config.server.git.hostKeyAlgorithm=ed25519
spring.cloud.config.server.git.privateKeyPath=/ssh/id_ed25519

spring.info.app.name=config-server
spring.info.description=config-server (local configuration)
spring.info.description.version=1.0.0

eureka.instance.hostname=${EUREKA_HOSTNAME}
eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=false

spring.cloud.config.server.git.clone-on-start=true
spring.cloud.config.server.git.force-pull=true
